name: destroy

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

env:
  ROCINANTE_KEY: "rocinante.key"
  GPG_ID: "126833D0A5DBB929717B4CFD5DD2E6DF5EE1E8E3"
  AWS_REGION: "eu-central-1"
  TERRAFORM_VERSION: "1.2.1"

jobs:

  CI_part:

    runs-on: ubuntu-latest

    steps:

    - name: Clone repository
      uses: actions/checkout@v3

    - name: Export ssh key
      run: |
        mkdir ./secret
        echo "${{ secrets.SSH_KEY }}" > ./secret/bochinskii_Frankfurt_2.pem
        chmod 0600 ./secret/bochinskii_Frankfurt_2.pem

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform
      run: |
        export AWS_ACCESS_KEY_ID="${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}"
        export AWS_DEFAULT_REGION="${{ env.AWS_REGION }}"
        export TF_VAR_site_dir="${{ secrets.SITE_DIR }}"
        export TF_VAR_mysql_root_pass="${{ secrets.MYSQL_ROOT_PASS }}"
        export TF_VAR_mysql_drupal_user_pass="${{ secrets.MYSQL_DRUPAL_USER_PASS }}"
        export TF_VAR_mysql_admin_user="${{ secrets.MYSQL_ADMIN_USER }}"
        export TF_VAR_mysql_drupal_user="${{ secrets.MYSQL_DRUPAL_USER }}"
        export TF_VAR_mysql_admin_user_pass="${{ secrets.MYSQL_ADMIN_USER_PASS }}"
        export TF_VAR_ssh_port="${{ secrets.SSH_PORT }}"
        export TF_VAR_mysql_drupal_db="${{ secrets.MYSQL_DRUPAL_DB }}"
        terraform version
        echo "##############"
        echo "TERRAFORM INIT"
        echo "##############"
        terraform init
        echo "##############"
        echo "TERRAFORM DESTROY"
        echo "##############"
        terraform destroy -auto-approve
