name: deploy_lemp_auto_terraform

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

env:
  AWS_DEFAULT_REGION: "eu-central-1"
  ROCINANTE_KEY: "rocinante.key"
  GPG_ID: "126833D0A5DBB929717B4CFD5DD2E6DF5EE1E8E3"

jobs:

  CI_part:

    runs-on: ubuntu-latest

    steps:

    - name: Clone repository
      uses: actions/checkout@v3

    - name: test gpg
      run: |
        gpg --version
