name: lemp

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

env:
  AWS_DEFAULT_REGION: "eu-central-1"
  ROCINANTE_KEY: "rocinante.key"
  GPG_ID: "126833D0A5DBB929717B4CFD5DD2E6DF5EE1E8E3"

jobs:

  CI_part:

    runs-on: ubuntu-latest

    steps:

    - name: Clone repository
      uses: actions/checkout@v3

    - name: test gpg
      run: |
        ls -l
        gpg --version

    - name: Export rocinante key
      run: |
        echo "${{ secrets.ROCINANTE_KEY }}" > ${ env.ROCINANTE_KEY }

    - name: Export ssh key
      run: |
        mkdir ./secret
        echo "${{ secrets.SSH_KEY }}" > ./secret/bochinskii_Frankfurt_2.pem
        chmod 0600 ./secret/bochinskii_Frankfurt_2.pem

    - name: Export and Import gpg key
      run: |
        echo "${{ secrets.GPG_KEY }}" > ./gpg/gpg.key
        gpg --import ./gpg/gpg.pub
        gpg --pinentry-mode=loopback --passphrase "${ secrets.GPG_PASSWORD }" --allow-secret-key-import --import ./gpg/gpg.key
        gpg --list-key ${{ env.GPG_ID }}
        gpg --list-secret-key ${{ env.GPG_ID }}
